pipelines:
  - name: basic
    steps:
      - name: basic1
        type: Bash
        configuration:
          inputResources:
            - name: git_vijay
          runtime:
            type: image
        execution:
          onExecute:
            - printenv {{ .Values.foo.bar }}
      - name: basic2
        type: Bash
        configuration:
          runtime:
            type: image
          inputSteps:
            - name: basic1
        execution:
          onExecute:
            - printenv {{ .Values.foo.bar }}

      {{ if eq "{{gitBranch}}" "release" }}
      - name: basic3
        type: Bash
        configuration:
          runtime:
            type: image
          inputSteps:
            - name: basic2
        execution:
          onExecute:
            - printenv {{ .Values.foo.bar }}
      {{ end }}
