template: true
valuesFilePath: pipelineValues.yml

resources:
  - name: git_vijay
    type: GitRepo
    configuration:
      gitProvider: vijay 
      path: vijayreddy1991/test_templates 
      branches:     
        include: ^{{gitBranch}}$ 

pipelines:
  - name: basic
    steps:
      - name: basic1
        type: Bash
        configuration:
          inputResources:
            - name: git_vijay
          runtime:
            type: image
        execution:
          onExecute:
            - printenv 
      - name: basic2
        type: Bash
        configuration:
          runtime:
            type: image
          inputSteps:
            - name: basic1
        execution:
          onExecute:
            - printenv 

      {{- if eq "{{gitBranch}}" "^release" }}
#       {{- if .Values.BuildInfo }}
      - name: basic3
        type: Bash
        configuration:
          runtime:
            type: image
          inputSteps:
            - name: basic2
        execution:
          onExecute:
            - printenv   
    {{- end }}              
